package sting.processor;

import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import javax.json.stream.JsonGenerator;
import javax.lang.model.element.Element;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import org.jspecify.annotations.Nullable;
import org.realityforge.proton.ElementsUtil;

final class Node {
    enum Kind {
        ROOT,
        BINDING,
        PROXY
    }

    /**
     * The component graph that created this node.
     */
    private final ComponentGraph _componentGraph;
    /**
     * The binding for the node.
     * May be null if it represents an Injector.
     */
    @Nullable
    private final Binding _binding;
    /**
     * The proxy descriptor for this node if it represents an intercepted service proxy.
     */
    @Nullable
    private final InterceptorProxyDescriptor _proxy;
    /**
     * The edges to nodes that this node depends upon.
     */
    private final Map<ServiceRequest, Edge> _dependsOn = new LinkedHashMap<>();
    /**
     * The edges to nodes that use this node.
     */
    private final Set<Edge> _usedBy = new HashSet<>();
    /**
     * True if the node is explicitly from an eager binding or implicitly eager by being
     * a (transitive) dependency of an eager binding.
     */
    private boolean _eager;
    /**
     * The shortest path from a top level dependency to this node.
     */
    private int _depth = Integer.MAX_VALUE;
    /**
     * Name within the context of the Injector. The name MUST be unique and will be generated by the processor.
     */
    @Nullable
    private String _name;
    /**
     * The java type of the value provided by the node.
     * this will be null if binding is null.
     */
    @Nullable
    private final TypeMirror _type;
    /**
     * Is the visibility of the type effectively public. This means that the type and
     * all enclosing types must have a public modifier.
     */
    private final boolean _public;
    /**
     * The Fragment node that this node is derived from if it is from a Fragment provider method.
     */
    @Nullable
    private FragmentNode _fragment;

    /**
     * Constructor used to construct a Node for the Injector.
     *
     * @param componentGraph the object graph
     */
    Node(final ComponentGraph componentGraph) {
        this(
                componentGraph,
                null,
                null,
                componentGraph.getInjector().getOutputs().toArray(new ServiceRequest[0]));
    }

    /**
     * Constructor used to construct a Node for a binding.
     *
     * @param binding the binding.
     */
    Node(final ComponentGraph componentGraph, final Binding binding) {
        this(componentGraph, binding, null, binding.getDependencies());
    }

    /**
     * Constructor used to construct a Node for an intercepted service proxy.
     *
     * @param componentGraph the object graph.
     * @param proxy          the proxy descriptor.
     */
    Node(final ComponentGraph componentGraph, final InterceptorProxyDescriptor proxy) {
        this(componentGraph, null, proxy, new ServiceRequest[0]);
    }

    private Node(
            final ComponentGraph componentGraph,
            @Nullable final Binding binding,
            @Nullable final InterceptorProxyDescriptor proxy,
            final ServiceRequest[] dependencies) {
        _componentGraph = Objects.requireNonNull(componentGraph);
        _binding = binding;
        _proxy = proxy;
        assert null == binding || null == proxy;
        for (final ServiceRequest dependency : dependencies) {
            _dependsOn.put(dependency, new Edge(this, dependency));
        }
        if (null != binding) {
            final Element element = binding.getElement();
            final Binding.Kind kind = binding.getKind();
            _type = Binding.Kind.INPUT == kind
                    ? binding.getPublishedServices().get(0).getCoordinate().type()
                    : Binding.Kind.INJECTABLE == kind
                            ? Objects.requireNonNull(element.getEnclosingElement())
                                    .asType()
                            : ((ExecutableElement) element).getReturnType();
            _public = TypeKind.DECLARED != _type.getKind()
                    || ElementsUtil.isEffectivelyPublic((TypeElement) ((DeclaredType) _type).asElement());
        } else if (null != _proxy) {
            _type = _proxy.getService().service().getCoordinate().type();
            _public = _proxy.getService().service().isPublic();
        } else {
            _type = null;
            _public = true;
        }
    }

    boolean isFromProvides() {
        return isBinding() && Binding.Kind.PROVIDES == getBinding().getKind();
    }

    Kind getKind() {
        return null != _binding ? Kind.BINDING : null != _proxy ? Kind.PROXY : Kind.ROOT;
    }

    boolean isBinding() {
        return Kind.BINDING == getKind();
    }

    boolean isProxy() {
        return Kind.PROXY == getKind();
    }

    String getId() {
        if (null != _binding) {
            return _binding.getId();
        } else if (null != _proxy) {
            return _proxy.getId();
        } else {
            return "injector";
        }
    }

    String getName() {
        return Objects.requireNonNull(_name);
    }

    void setName(final String name) {
        _name = Objects.requireNonNull(name);
    }

    TypeMirror getType() {
        return Objects.requireNonNull(_type);
    }

    boolean isPublic() {
        return _public;
    }

    boolean isEager() {
        return _eager;
    }

    boolean isDeclaredEager() {
        return null != _binding
                ? _binding.isEager()
                : null != _proxy && _proxy.getService().binding().isEager();
    }

    void markNodeAndUpstreamAsEager() {
        if (!_eager) {
            _eager = true;
            // Propagate eager flag to all nodes that this node uses unless
            // the service is a Supplier style service. Those can be non-eager
            // as they do not need to be created until they are accessed
            for (final Edge edge : _dependsOn.values()) {
                if (!edge.getServiceRequest().getKind().isSupplier()) {
                    edge.getSatisfiedBy().forEach(Node::markNodeAndUpstreamAsEager);
                }
            }
        }
    }

    boolean hasNoBinding() {
        return null == _binding;
    }

    Binding getBinding() {
        return Objects.requireNonNull(_binding);
    }

    Binding getProviderBinding() {
        return null != _binding ? _binding : getProxy().getService().binding();
    }

    InterceptorProxyDescriptor getProxy() {
        return Objects.requireNonNull(_proxy);
    }

    Collection<Edge> getDependsOn() {
        return _dependsOn.values();
    }

    Set<Edge> getUsedBy() {
        return _usedBy;
    }

    boolean isDepthNotSet() {
        return Integer.MAX_VALUE == _depth;
    }

    int getDepth() {
        return _depth;
    }

    void setDepth(final int depth) {
        _depth = depth;
    }

    void usedBy(final Edge edge) {
        assert !_usedBy.contains(edge);
        _usedBy.add(edge);
    }

    void setFragment(final FragmentNode fragment) {
        assert isFromProvides();
        assert null == _fragment;
        _fragment = fragment;
    }

    FragmentNode getFragment() {
        return Objects.requireNonNull(_fragment);
    }

    /**
     * Describe a node as a single line.
     * Typically this is used when emitting messages to user.
     *
     * @param connector a 3-character string that appears between type label and the node description. Typically
     *                  used for describing connectors between successive nodes.
     * @return the string description.
     */
    String describe(final String connector) {
        return "  " + getTypeLabel() + connector + " " + describeBinding();
    }

    String getTypeLabel() {
        return null != _binding ? _binding.getTypeLabel() : null != _proxy ? "[Proxy]      " : "[Injector]   ";
    }

    String describeBinding() {
        return null != _binding
                ? _binding.describe()
                : null != _proxy
                        ? _proxy.getId()
                        : _componentGraph
                                .getInjector()
                                .getElement()
                                .getQualifiedName()
                                .toString();
    }

    void addResolvedDependency(final ServiceRequest serviceRequest, final Node node) {
        final var edge = new Edge(this, serviceRequest);
        edge.setSatisfiedBy(Collections.singletonList(node));
        _dependsOn.put(serviceRequest, edge);
    }

    void write(final JsonGenerator g) {
        g.writeStartObject();
        g.write("id", getId());
        if (null != _binding) {
            final Binding.Kind kind = _binding.getKind();
            g.write("kind", kind.name());
        } else {
            final var proxy = getProxy();
            g.write("kind", "PROXY");
            g.writeStartObject("service");
            proxy.getService().service().getCoordinate().write(g);
            g.writeEnd();
        }
        if (_eager) {
            g.write("eager", true);
        }
        if (null != _proxy) {
            g.write("target", _proxy.getService().binding().getId());
            final List<Binding> interceptors = _proxy.getGenericInterceptorBindings();
            if (!interceptors.isEmpty()) {
                g.writeStartArray("interceptors");
                for (final Binding binding : interceptors) {
                    g.write(binding.getId());
                }
                g.writeEnd();
            }
        }
        if (!_dependsOn.isEmpty()) {
            g.writeStartArray("dependencies");
            for (final Edge edge : _dependsOn.values()) {
                g.writeStartObject();
                edge.getServiceRequest().getService().getCoordinate().write(g);
                g.writeStartArray("supportedBy");
                for (final Node node : edge.getSatisfiedBy()) {
                    g.write(node.getId());
                }
                g.writeEnd();
                g.writeEnd();
            }
            g.writeEnd();
        }
        g.writeEnd();
    }
}
